### ISSUE TITLE
Fatal error: Can't use library

### ISSUE THREAD

**Issue by hipper** [jukylin/jaeger-php#17]
Hey guys, 
I've just installed you lib via composer as per documentation.

I've got:
- opentracing/opentracing (1.0-beta1)
- jukylin/jaeger-php (v2.0.0-beta)

Now, when I use it I see the following PHP Fatal error:
```
Xdebug: Fatal error: Declaration of Jaeger\Jaeger::inject(OpenTracing\SpanContext $spanContext, $format, &$carrier) must be compatible with OpenTracing\Tracer::inject(OpenTracing\SpanContext $spanContext, $format, OpenTracing\Propagators\Writer $carrier) in /srv/vendor/jukylin/jaeger-php/src/Jaeger/Jaeger.php on line 13.
```

It looks like package versions are not compatible. Can you please let me know if this is a known issue?

Thanks

**Comment by ilufei** [comment]
I get the problem too ...

**Comment by jukylin** [comment]
Sorry , you can use  opentracing/opentracing (1.0.0-beta2)

**Comment by hipper** [comment]
Not sure about that... tried to replace thewhole dir and it didn’t help :(

**Comment by jukylin** [comment]
What's your installation step.

**Comment by hipper** [comment]
I install it via composer, if I use `1.0.0-beta2` like this:
```
"require": {
        "opentracing/opentracing":"1.0.0-beta2",
        "jukylin/jaeger-php" : "v2.0.0-beta"
	}
```

I'll get an error:
`- jukylin/jaeger-php v2.0.0-beta requires opentracing/opentracing 1.0-beta1 -> satisfiable by opentracing/opentracing[1.0-beta1]`

If I just replace the opentracing vendor folder with contents from `1.0.0-beta2` I still see the same error message.

P.S: I can't use `  "minimum-stability": "dev",` on prod, that's not an option.

**Comment by jukylin** [comment]
[fix bug](https://github.com/jukylin/jaeger-php/commit/eed11b7fce8119d6c8291fa4ee561a8d0cd16564), but  you have to use ```"minimum-stability": "dev"```, It's not a stable.

**Comment by hipper** [comment]
Hey @jukylin, thanks for fixing it!
