### ISSUE TITLE
Opentracing beta5 version

### ISSUE THREAD

**Issue by piotrooo** [jukylin/jaeger-php#21]
Hello,
there are any plans about implement a newest version of the opentracing API - beta5?

**Comment by jukylin** [comment]
Not sure,I don't know its role.

**Comment by monteiro** [comment]
@jukylin hi! great library here.

Do you have any plans to upgrade to the latest beta5 of [opentracing api](https://github.com/opentracing/opentracing-php)?

Just asking :)

One of the things that I miss is an easy way for active span management so you don't have to reference always the root span all the time.

**Comment by jukylin** [comment]
done [v2.0.8-beta](https://github.com/jukylin/jaeger-php/releases/tag/v2.0.8-beta)

**Comment by monteiro** [comment]
Thanks a lot!
