### ISSUE TITLE
Tracing AMQP Workflow

### ISSUE THREAD

**Issue by Mulkave** [jukylin/jaeger-php#28]
For a workflow as follows:

```
Start (Service A) -- amqp --> General Processing (Service B) ---
--- amqp --> Fork into two queues Task C (Service C) and D (Service D)
```

The exact similar case of https://github.com/jaegertracing/jaeger-client-python/issues/122

From the code examples:

```php
$tracer = $config->initTrace('Service A', '0.0.0.0:6831');
$spanContext = $tracer->extract(Formats\TEXT_MAP, $_SERVER);

$serverSpan = $tracer->startSpan('get data', ['child_of' => $spanContext]);
$serverSpan->addBaggageItem("version", "1.6.0");

$tracer->inject($serverSpan->getContext(), Formats\TEXT_MAP, $_SERVER);

```

**Questions**
1. what does `extract(Formats\TEXT_MAP, $_SERVER)` achieve?
2. Is it the server's `spanContext` that needs to be shared across all services and have them bi `child_of` of it?
2. How would you recommend to share a trace that goes from `Service A` to `Service D` to cover the mentioned workflow?

Much appreciated!

**Comment by jukylin** [comment]
Does amqp implement Distributed Tracing?

**Comment by Mulkave** [comment]
Not with PHP, no. There is a Go package for that though https://github.com/opentracing-contrib/go-amqp not sure if it helps (new to this realm, sorry).

On the other hand, it is not necessary to track within AMQP, what matters is to trace the spans in the services (it's alright to skip AMQP for tracing).

Would that work? i.e. if we were to pass the SpanContext through message headers of AMQP somehow?

**Comment by jukylin** [comment]
I think you need to inject ```SpanContext``` to  message body. Like this： Service A： ```
$tracer->inject($serverSpan->getContext(), Formats\TEXT_MAP, $amqpMsg) ``` and Service C : ```$tracer->extract(Formats\TEXT_MAP, $amqpMsg)```
