### ISSUE TITLE
ScopeManager.delactivate misspelled

### ISSUE THREAD

**Issue by nkhoshini** [jukylin/jaeger-php#52]
See https://github.com/jukylin/jaeger-php/blob/51b6f403b410c3e7c14d7ee613d065e6c08190f9/src/Jaeger/ScopeManager.php#L42

It is specified as **deactivate** in the PHP OpenTracing library here:
https://github.com/opentracing/opentracing-php/blob/1.0.0-beta5/src/OpenTracing/Mock/MockScopeManager.php#L38

**Comment by jukylin** [comment]
yes，beacuse I think **deactivate** is indistinct. decode activate or delete activate ?

**Comment by nkhoshini** [comment]
It is undoing the work of **activate** technically so deactivate makes sense. However I suppose **removeActive** or **deleteActive** makes sense as well.

**Comment by jukylin** [comment]
done #53
