### ISSUE TITLE
Update dev-master on packagist

### ISSUE THREAD

**Issue by dmnbars** [jukylin/jaeger-php#67]
Hello.

Can you update `dev-master` on packagist.org?
It is referencing to old commit https://github.com/jukylin/jaeger-php/commit/09178cd69dd633bcc82e1ad8a16e7f902a002d2f.

**Comment by dmnbars** [comment]
Or maybe you have plan about release new tagged version?

**Comment by jukylin** [comment]
Yes, I want release new tagged version with December 1st

**Comment by dmnbars** [comment]
Thanks a lot
