### ISSUE TITLE
is this can not support golang to php?

### ISSUE THREAD

**Issue by 130-133** [jukylin/jaeger-php#72]
it is pretty good supporting php to php, but i found that golang (or other language or platform like postman) to php is sure when error occured. And i can not find datas by a correct request. so why? or that is there any other config operation i ignored to do？
Thanks ：）

**Comment by jukylin** [comment]
show your code and error

**Comment by 130-133** [comment]
no errors, just can't find interface requests chains records from golang or postman.
so i wonder if some configs i ingored to set.

**Comment by 130-133** [comment]
> show your code and error it will not record if i use exit to finish a function.
