### ISSUE TITLE
uber-trace-id 能不能换个常量？

### ISSUE THREAD

**Issue by luis360** [jukylin/jaeger-php#73]
const Tracer_State_Header_Name = 'uber-trace-id';
const Trace_Baggage_Header_Prefix = 'uberctx-';
这两个带uber了 不好吧，能不能换个其他的

**Comment by jukylin** [comment]
这是为了兼容Jaeger其他的客户端

**Comment by luis360** [comment]
用到自己项目里 header上带个uber 好奇怪哦
