### ISSUE TITLE
接入jaeger-php出现性能损耗

### ISSUE THREAD

**Issue by wgb1990** [jukylin/jaeger-php#83]
我们这边接入jaeger发现性能损耗在30%-50%，大家有遇到过吗？

**Comment by jukylin** [comment]
具体描述下你是怎么接入的用了什么采集策略？php-fpm？ swoole？还有php对应的版本

**Comment by wgb1990** [comment]
使用的是php-fpm，php版本：5.6

**Comment by wgb1990** [comment]
> 具体描述下你是怎么接入的用了什么采集策略？php-fpm？ swoole？还有php对应的版本

使用的是php-fpm，php版本：5.6

**Comment by jukylin** [comment]
没有其他反馈我就关闭了
