### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by cawolf** [jukylin/jaeger-php#87]
Hi,

when do you plan releasing the next version of you library? We would like to operate at least on `beta` versions instead of `dev-master`.

Thanks,
best regards, @cawolf

**Comment by jukylin** [comment]
Sorry, I reply late, I am currently working on a new project. I usually release after fixing multiple bugs

**Comment by jukylin** [comment]
done [v2.1.1-beta](https://github.com/jukylin/jaeger-php/releases/tag/v2.1.1-beta)

**Comment by cawolf** [comment]
Thank you very much :+1:
