### ISSUE TITLE
"minimum-stability": "dev" => to stable

### ISSUE THREAD

**Issue by quebello** [jukylin/jaeger-php#92]
Hello,

Is it possible to do a release with the "minimum-stability": "stable" ? and when you can do that ?

Kind regards

**Comment by weixuan19930** [comment]
+1

**Comment by jukylin** [comment]
Sorry for late reply. Actually, I wanted to release a stable version for a long time, It's just that I need to wait for opentracing-php release stable version first. Done [v2.1.3](https://github.com/jukylin/jaeger-php/releases/tag/v2.1.3)

**Comment by quebello** [comment]
@jukylin  thank you

**Comment by quebello** [comment]
@jukylin any update ?

**Comment by jukylin** [comment]
Wath do you mean ? I have released a stable version [v2.1.3](https://github.com/jukylin/jaeger-php/releases/tag/v2.1.3)

**Comment by quebello** [comment]
In your version 2.1.3, you use the version     "opentracing/opentracing" : "1.0.0-beta5"
But this one use a minimum stability dev.

With the Version 1.0.0-beta6  => the minimum stability is stable !!! Then you can switch in you composer to this version no ?

**Comment by dmnbars** [comment]
if I understand the [documentation](https://getcomposer.org/doc/articles/versions.md) correctly 1.0.0-beta* versions is not stable. Only 1.0.0 would be stable.

**Comment by dmnbars** [comment]
config `minimum-stability` in root composer.json only for install deps for current package:
https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by quebello** [comment]
In my composer.json

` "minimum-stability": "stable",
  "require": {
    "guzzlehttp/guzzle": "^6.5",
    "illuminate/support": "^6.0",
    "jukylin/jaeger-php": "2.1.3",
    "rtbf/lumen-support": "^2.0"
  },`


$ composer install
Loading composer repositories with package information                                                                                                                                                                  Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jukylin/jaeger-php 2.1.3 -> satisfiable by jukylin/jaeger-php[v2.1.3].
    - jukylin/jaeger-php v2.1.3 requires opentracing/opentracing 1.0.0-beta5 -> satisfiable by opentracing/opentracing[1.0.0-beta5] but these conflict with your requirements or minimum-stability.

**Comment by quebello** [comment]
Ok it works if i had this in the composer.json

```
    "jukylin/jaeger-php": "2.1.3",
    "opentracing/opentracing": "1.0.0-beta5",
```
